INFO  | File run_exp_local.py     | Line 16    | Writing log file to ./exp\GTS_1_0222_020050\log_exp_1010.txt
INFO  | File run_exp_local.py     | Line 17    | Exp instance id = GTS_1_0222_020050
ERROR | File run_exp_local.py     | Line 25    | Traceback (most recent call last):
  File "C:\Users\KimJuHyeon\GSL\run_exp_local.py", line 21, in main
    runner.train()
  File "C:\Users\KimJuHyeon\GSL\runner\GTS_runner.py", line 109, in train
    _, outputs = self.model(data_batch.x, data_batch.y, self.entire_inputs, self.init_edge_index)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\GSL\models\GTS\GTS_model.py", line 85, in forward
    adj = self.graph_learning(entire_inputs, edge_index)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\GSL\models\GTS\self_attention_graph_learning.py", line 76, in forward
    outputs = self.attention_gl(x, x)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\GSL\models\Attention.py", line 62, in forward
    attn = self.attention(qs, ks, mask)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\GSL\models\Attention.py", line 13, in forward
    attn = torch.bmm(q, torch.transpose(k))
TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


