INFO  | File run_exp_local.py     | Line 15    | Writing log file to ./exp\GTS_1_0111_102004\log_exp_1010.txt
INFO  | File run_exp_local.py     | Line 16    | Exp instance id = GTS_1_0111_102004
ERROR | File run_exp_local.py     | Line 24    | Traceback (most recent call last):
  File "C:\Users\KimJuHyeon\GSL\run_exp_local.py", line 20, in main
    runner.train()
  File "C:\Users\KimJuHyeon\GSL\runner\GTS_runner.py", line 109, in train
    _, outputs = self.model(data_batch.x, data_batch.y, self.entire_inputs, self.init_edge_index)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\GSL\models\GTS\GTS_model.py", line 40, in forward
    adj = self.graph_learning(entire_inputs, edge_index)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\GSL\models\GTS\gts_graph_learning.py", line 58, in forward
    x = self.conv1(x)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\KimJuHyeon\anaconda3\envs\GraphStructureLEarning\lib\site-packages\torch\nn\modules\conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 3-dimensional input for 3-dimensional weight [4, 1, 200], but got 1-dimensional input of size [100] instead

