INFO  | File run_exp_local.py     | Line 15    | Writing log file to ./exp\GTS_1_0110_043239\log_exp_1010.txt
INFO  | File run_exp_local.py     | Line 16    | Exp instance id = GTS_1_0110_043239
ERROR | File run_exp_local.py     | Line 25    | Traceback (most recent call last):
  File "C:\Users\KimJuHyeon\GSL\run_exp_local.py", line 19, in main
    runner = GTS_Runner(config=config)
  File "C:\Users\KimJuHyeon\GSL\runner\GTS_runner.py", line 84, in __init__
    self.graph_forecasting = GTS_Forecasting_Module(self.config)
  File "C:\Users\KimJuHyeon\GSL\models\GTS\gts_forecasting_module.py", line 100, in __init__
    self.output_dim = config.output_dim
AttributeError: 'EasyDict' object has no attribute 'output_dim'

