INFO  | File run_exp_CCN_Project.py | Line 15    | Writing log file to ./exp/GTS_test_1217_164520/log_exp_1010.txt
INFO  | File run_exp_CCN_Project.py | Line 16    | Exp instance id = GTS_test_1217_164520
ERROR | File run_exp_CCN_Project.py | Line 25    | Traceback (most recent call last):
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/run_exp_CCN_Project.py", line 19, in main
    runner = GTS_Runner(config=config)
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/runner/CCN_Project_runner.py", line 50, in __init__
    self.train_dataset = self.prepare_dataset(self.train_entire)
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/runner/CCN_Project_runner.py", line 77, in prepare_dataset
    one_cell_inputs = dataset[target, trial, :,
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

