INFO  | File run_exp_CCN_Project.py | Line 15    | Writing log file to ./exp/GTS_test_1222_173400/log_exp_1010.txt
INFO  | File run_exp_CCN_Project.py | Line 16    | Exp instance id = GTS_test_1222_173400
ERROR | File run_exp_CCN_Project.py | Line 25    | Traceback (most recent call last):
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/run_exp_CCN_Project.py", line 20, in main
    runner.train()
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/runner/CCN_Project_runner.py", line 136, in train
    _, outputs, angle = self.model(inputs=data_batch.x, edge_index=data_batch.edge_index)
  File "/opt/anaconda3/envs/GraphStructureLearning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/models/GTS/GTS_model_for_CNN_Project.py", line 121, in forward
    for ii in self.decode_dim:
TypeError: 'int' object is not iterable

