INFO  | File run_exp_local.py     | Line 15    | Writing log file to ./exp\GTS_1_0110_043049\log_exp_1010.txt
INFO  | File run_exp_local.py     | Line 16    | Exp instance id = GTS_1_0110_043049
ERROR | File run_exp_local.py     | Line 25    | Traceback (most recent call last):
  File "C:\Users\KimJuHyeon\GSL\run_exp_local.py", line 19, in main
    runner = GTS_Runner(config=config)
  File "C:\Users\KimJuHyeon\GSL\runner\GTS_runner.py", line 63, in __init__
    total_dataset = dataset_maker.make()
  File "C:\Users\KimJuHyeon\GSL\dataset\make_datset.py", line 96, in make
    pickle.dump(data_dict, open(self.save_dir, 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: './data/spike_lambda_bin100/spike_lambda_bin100_2005050'

